# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: ghcr.io/silverstripeltd/bespoke-ci-base:3.2.1
        environment:
          - DISPLAY=:99
          - CHROME_BIN=/usr/bin/google-chrome-stable
          - BASH_ENV=/root/.bashrc
      - image: cimg/mysql:5.7
        environment:
          - MYSQL_ROOT_PASSWORD=ubuntu
          - MYSQL_DATABASE=circle_test
          - MYSQL_HOST=127.0.0.1

    working_directory: /var/www/mysite/www

    steps:
      # Use correct php version
      - run: php-switch 7.4

      # Start Apache, Nginx and Xvfb
      - run: sudo service apache2 start
      - run: sudo service nginx start
      - run:
          command: Xvfb :99 -screen 0 1280x1024x24
          background: true

      - checkout

      # Use correct node version
      - run: nvm alias default $(cat .nvmrc)

      # Composer Installation
      - run: composer self-update --2
      - run: composer install -n --prefer-source --no-interaction
#      - run: composer vendor-expose # always expose for extra safety

      - run: mv .circleci/.env.circleci .env
      - run: chown -R vagrant:vagrant /var/www/mysite/www
      - run: chmod g+s /var/www/mysite/www

      # JS/SCSS/PHP Linting
      - run: composer silverstripe-standards

      # shoe-horn in Page and PageController
      - run: cp /var/www/mysite/www/tests/php/templates/PageController.php.tmpl /var/www/mysite/www/src/PageController.php
      - run: cp /var/www/mysite/www/tests/php/templates/Page.php.tmpl /var/www/mysite/www/src/Page.php

      # dev/build
      - run: sudo -u vagrant vendor/bin/sake dev/build flush=1

      # PHP Tests
      - run: vendor/bin/phpunit --verbose
